### PR TITLE
Bevy 0.15

### PR DESCRIPTION
**Pull request by ptsd**
Hi there,

First of all thanks for an awesome package 👍 

I'm working on a project and in the middle of preparing for bevy 0.15 and thought I might as well share my in-progress work.

bevy_rapier has no 0.15 support yet so that's still outstanding. I have my own fork of bevy_rapier and rapier that works but best to wait for the upstream changes. The nalgebra stuff for glam29 got merged so presumably not too far away 😄 

Also fixed a few issues with `Rectangle` vs `Plane3d` and rotation and added a multi floor example for avian.

There are some CI changes I found useful for my own testing I've added as well, feel free to ignore them 🤷 

Main changes:
- [x] Update bevy deps to 0.15
- [x] Update parry3d dep to 0.17 as both avian3d and rapier3d will be on 0.17 for bevy-0.15
- [x] Remove the parry3d feature matrix stuff
- [x] Update avian3d dep to git/main for now
- [x] Update nalgebra dep to 0.33 for the `convert-glam029` feature support
- [x] Update parry3d example / tests as required
- [x] Update avian3d example / tests as required
- [x] Update parry3d workflow for changed features
- [x] Couple of spelling / wording changes
- [x] Update bevy_rapier3d dep
- [x] Update rapier3d example / tests as required

Other changes:
- [x] Add test_benches to CI (Ensures benches at least compile/run for commit)
- [x] Add run_benches to CI with manual trigger
- [x] Move CI tests to nextest with junit reporting  
- [x] Tweak CI run conditions to avoid double test runs for pushes to branches in PR
- [x] Update CI runs for separate run / report workflows as per discussion below (see https://github.com/TheGrimsey/oxidized_navigation/pull/36)
- [x] Add multi floor example for Avian
- [x] Add `bevy_window` to dev bevy features
- [x] Update `MIGRATING.md` for 0.12.0
- [x] Update `README.md` for 0.12.0 

TODO:
- [x] Remove crates-io patch for `bevy_rapier3d` when upstream updates
- [ ] Remove crates-io patch for `avian3d` when upstream updates

### CODE REVIEW

**Comment by TheGrimsey** [comment]
Fantastic! 

Huge props for actually fixing the issues with the examples. I should've done that a while ago :sweat_smile: 

Very interested in seeing those CI changes :eyes:

**Comment by ptsd** [comment]
👍 
Looks like it's the test reporting thats failing. Are you using a scoped token / PAT for your action runs maybe?

https://github.com/mikepenz/action-junit-report/issues/23

Was also wondering if it would be better splitting the backends into seperate `cargo.toml` only style crates ala `bevy_mod_picking` / `rapier`? Happy to do that as part of this if you think it's worthwhile?

**Comment by TheGrimsey** [comment]
> Are you using a scoped token / PAT for your action runs maybe?

I have none set at all 🤔 

Ah, need to set [permissions in the workflow for PRs checks](https://github.com/mikepenz/action-junit-report?tab=readme-ov-file#pr-run-permissions) to function.

> Was also wondering if it would be better splitting the backends into seperate cargo.toml only style crates ala bevy_mod_picking / rapier? Happy to do that as part of this if you think it's worthwhile?

Is that possible with the trait? Isn't blocked by the orphan rule?

**Comment by ptsd** [comment]
> Ah, need to set [permissions in the workflow for PRs checks](https://github.com/mikepenz/action-junit-report?tab=readme-ov-file#pr-run-permissions) to function.

👍 

> Is that possible with the trait? Isn't blocked by the orphan rule?

Yeah noticed that after playing with splitting it out 🤷‍♂️

**Comment by ptsd** [comment]
@TheGrimsey 

So as per above I've split out the test / report test bits of the workflow to allow for posting checks. This is a bit of a rigamarole as it requires merging the dependent PR (https://github.com/TheGrimsey/oxidized_navigation/pull/36) before this.

The action token permissions for public fork based PRs are hard read only, so the workflows that actually publish the reports have to pre-exist in the root repository to work around that limitation.

I've also removed the pr comment feature as that requires even more messing around with run contexts to determine the correct PR to post to in the dependent workflows. 

These changes do also introduce some small security concerns but the reporting workflows are scoped to only `checks: write` and you don't allow automatic runs for fork based PRs so this seems fine?

Honestly this feels a bit overboard for the current test setup but presumably the plan is to add more coverage? I have a few tests around my own usage that are relevant but need some tidy-up to be generally applicable.

Also for some reason all the reports show up as triggered by the `Test Avian` workflow but they end up in the correct place so meh...

Up to you which way you want to proceed 🤷‍♂️. Happy to strip this back to just the actual 0.15 changes if you'd prefer?

**Comment by TheGrimsey** [comment]
> These changes do also introduce some small security concerns but the reporting workflows are scoped to only checks: write and you don't allow automatic runs for fork based PRs so this seems fine?

Yeah, runs need approval so it should be fine.

> Honestly this feels a bit overboard for the current test setup but presumably the plan is to add more coverage? I have a few tests around my own usage that are relevant but need some tidy-up to be generally applicable.

Yup yup. I need to get writing more tests 😅 

I'll go for it. Can always delete it if it does not do well

**Comment by occuros** [comment]
will this be merged soon as bevy 0.15 just came out?

**Comment by ptsd** [comment]
> will this be merged soon as bevy 0.15 just came out?

Still waiting on upstream changes for now:

> - [ ] Remove crates-io patch for `bevy_rapier3d` when upstream updates
> - [ ] Remove crates-io patch for `avian3d` when upstream updates

If you want to use while we wait I suggest:

Using parry3d:
```toml
[dependencies]
oxidized_navigation = { version = "0.12", default_features = false, features = ["parry3d"] }

[patch.crates-io]
oxidized_navigation = { git = "https://github.com/ptsd/oxidized_navigation.git", branch = "bevy-0.15" }
```

Using avian3d:
```toml
[dependencies]
oxidized_navigation = { version = "0.12", default_features = false, features = ["avian"] }
avian3d = { version = "0.1" }

[patch.crates-io]
oxidized_navigation = { git = "https://github.com/ptsd/oxidized_navigation.git", branch = "bevy-0.15" }
avian3d = { git = "https://github.com/Jondolf/avian.git", branch = "main" }
```

Using rapier3d (note the changes are upstream but no release tag as of yet):
```toml
[dependencies]
oxidized_navigation = { version = "0.12", default_features = false, features = ["rapier"] }
bevy_rapier3d = { version = "0.27" }

[patch.crates-io]
oxidized_navigation = { git = "https://github.com/ptsd/oxidized_navigation.git", branch = "bevy-0.15" }
bevy_rapier3d = { git = "https://github.com/Vrixyz/bevy_rapier.git", branch = "master-bevy_0.15" }
```

**Comment by ptsd** [comment]
@TheGrimsey 

I've reworked the CI stuff to a single matrix based workflow and added lints (`fmt / check / clippy`).

You can see an example run with a couple of failures @ https://github.com/ptsd/oxidized_navigation/actions/runs/12130725865

Would be good to get the other prep PR merged 👍  

Marking as ready for review as we are just awaiting upstream...

**Review by TheGrimsey — APPROVED** [review]

**Comment by ptsd** [comment]
@TheGrimsey 

Honestly might be better to just release this as the last thing is avian upstream and anyone wanting to use that backend is going to have to depend on the git version anyway 🤷.

I've updated `README.md` and `MIGRATING.md` as appropriate to explain this.

Then come back and remove the override when they update and release a `0.12.1`.

**Pull request merged**
